export const MAX_GUESSES = 6

export const PREFIXES = [
  { value: 'un', type: 'prefix', meaning: 'not, opposite of' },
  { value: 're', type: 'prefix', meaning: 'again, back' },
  { value: 'pre', type: 'prefix', meaning: 'before' },
  { value: 'dis', type: 'prefix', meaning: 'not, opposite of' },
  { value: 'mis', type: 'prefix', meaning: 'wrongly, badly' },
  { value: 'in', type: 'prefix', meaning: 'not, into' },
  { value: 'im', type: 'prefix', meaning: 'not' },
  { value: 'ir', type: 'prefix', meaning: 'not' },
  { value: 'il', type: 'prefix', meaning: 'not' },
  { value: 'non', type: 'prefix', meaning: 'not' },
  { value: 'anti', type: 'prefix', meaning: 'against' },
  { value: 'de', type: 'prefix', meaning: 'down, remove' },
  { value: 'over', type: 'prefix', meaning: 'too much, above' },
  { value: 'under', type: 'prefix', meaning: 'too little, below' },
  { value: 'out', type: 'prefix', meaning: 'beyond, more than' },
  { value: 'sub', type: 'prefix', meaning: 'under, below' },
  { value: 'super', type: 'prefix', meaning: 'above, beyond' },
  { value: 'trans', type: 'prefix', meaning: 'across, beyond' },
  { value: 'inter', type: 'prefix', meaning: 'between, among' },
  { value: 'semi', type: 'prefix', meaning: 'half, partly' },
  { value: 'mid', type: 'prefix', meaning: 'middle' },
  { value: 'co', type: 'prefix', meaning: 'together, with' },
  { value: 'ex', type: 'prefix', meaning: 'out of, former' },
  { value: 'en', type: 'prefix', meaning: 'cause to, put into' },
  { value: 'em', type: 'prefix', meaning: 'cause to, put into' },
]

export const SUFFIXES = [
  { value: 'able', type: 'suffix', meaning: 'can be done' },
  { value: 'ible', type: 'suffix', meaning: 'can be done' },
  { value: 'al', type: 'suffix', meaning: 'relating to' },
  { value: 'ial', type: 'suffix', meaning: 'relating to' },
  { value: 'ness', type: 'suffix', meaning: 'state of being' },
  { value: 'ment', type: 'suffix', meaning: 'action or process' },
  { value: 'tion', type: 'suffix', meaning: 'action or process' },
  { value: 'sion', type: 'suffix', meaning: 'action or process' },
  { value: 'ful', type: 'suffix', meaning: 'full of' },
  { value: 'less', type: 'suffix', meaning: 'without' },
  { value: 'ly', type: 'suffix', meaning: 'in a way, manner' },
  { value: 'er', type: 'suffix', meaning: 'one who, more' },
  { value: 'or', type: 'suffix', meaning: 'one who' },
  { value: 'ist', type: 'suffix', meaning: 'one who practices' },
  { value: 'est', type: 'suffix', meaning: 'most' },
  { value: 'ing', type: 'suffix', meaning: 'action in progress' },
  { value: 'ed', type: 'suffix', meaning: 'past tense' },
  { value: 'ous', type: 'suffix', meaning: 'full of, having' },
  { value: 'ious', type: 'suffix', meaning: 'full of, having' },
  { value: 'ive', type: 'suffix', meaning: 'having nature of' },
  { value: 'ity', type: 'suffix', meaning: 'state, quality' },
  { value: 'ty', type: 'suffix', meaning: 'state, quality' },
  { value: 'ism', type: 'suffix', meaning: 'belief, practice' },
  { value: 'ship', type: 'suffix', meaning: 'state, condition' },
  { value: 'dom', type: 'suffix', meaning: 'state, realm' },
  { value: 'hood', type: 'suffix', meaning: 'state, condition' },
  { value: 'ward', type: 'suffix', meaning: 'direction' },
  { value: 'ize', type: 'suffix', meaning: 'to make, become' },
  { value: 'ify', type: 'suffix', meaning: 'to make, become' },
  { value: 'en', type: 'suffix', meaning: 'to make, become' },
]

export const ROOTS = [
  // Common everyday roots
  { value: 'happy', type: 'root', meaning: 'feeling joy' },
  { value: 'comfort', type: 'root', meaning: 'ease, support' },
  { value: 'play', type: 'root', meaning: 'engage in activity' },
  { value: 'break', type: 'root', meaning: 'separate into pieces' },
  { value: 'agree', type: 'root', meaning: 'have same opinion' },
  { value: 'believe', type: 'root', meaning: 'accept as true' },
  { value: 'care', type: 'root', meaning: 'feel concern' },
  { value: 'help', type: 'root', meaning: 'assist' },
  { value: 'hope', type: 'root', meaning: 'expect with desire' },
  { value: 'kind', type: 'root', meaning: 'gentle, caring' },
  { value: 'thought', type: 'root', meaning: 'idea, reflection' },
  { value: 'wonder', type: 'root', meaning: 'amazement' },
  { value: 'power', type: 'root', meaning: 'strength, ability' },
  { value: 'self', type: 'root', meaning: 'one\'s own person' },
  { value: 'friend', type: 'root', meaning: 'person you like' },
  { value: 'thank', type: 'root', meaning: 'express gratitude' },
  { value: 'trust', type: 'root', meaning: 'believe in' },
  { value: 'use', type: 'root', meaning: 'employ, utilize' },
  { value: 'work', type: 'root', meaning: 'labor, effort' },
  { value: 'place', type: 'root', meaning: 'location' },
  { value: 'move', type: 'root', meaning: 'change position' },
  { value: 'build', type: 'root', meaning: 'construct' },
  { value: 'read', type: 'root', meaning: 'interpret text' },
  { value: 'write', type: 'root', meaning: 'form letters' },
  { value: 'speak', type: 'root', meaning: 'talk, say' },
  { value: 'think', type: 'root', meaning: 'use mind' },
  { value: 'know', type: 'root', meaning: 'be aware of' },
  { value: 'like', type: 'root', meaning: 'similar, enjoy' },
  { value: 'love', type: 'root', meaning: 'deep affection' },
  { value: 'fear', type: 'root', meaning: 'be afraid' },
  { value: 'doubt', type: 'root', meaning: 'uncertainty' },
  { value: 'count', type: 'root', meaning: 'enumerate' },
  { value: 'cover', type: 'root', meaning: 'put over' },
  { value: 'respect', type: 'root', meaning: 'admiration' },
  { value: 'connect', type: 'root', meaning: 'join together' },
  { value: 'appear', type: 'root', meaning: 'come into view' },
  { value: 'arrange', type: 'root', meaning: 'put in order' },
  { value: 'fashion', type: 'root', meaning: 'style, make' },
  { value: 'fortune', type: 'root', meaning: 'luck, wealth' },
  { value: 'grace', type: 'root', meaning: 'elegance' },
  { value: 'honest', type: 'root', meaning: 'truthful' },
  { value: 'loyal', type: 'root', meaning: 'faithful' },
  { value: 'patient', type: 'root', meaning: 'able to wait' },
  { value: 'peace', type: 'root', meaning: 'calm, no conflict' },
  { value: 'perfect', type: 'root', meaning: 'without flaw' },
  { value: 'polite', type: 'root', meaning: 'courteous' },
  { value: 'proper', type: 'root', meaning: 'correct, suitable' },
  { value: 'pure', type: 'root', meaning: 'clean, unmixed' },
  { value: 'safe', type: 'root', meaning: 'free from danger' },
  { value: 'fair', type: 'root', meaning: 'just, equal' },
  { value: 'firm', type: 'root', meaning: 'solid, strong' },
  { value: 'fit', type: 'root', meaning: 'suitable, healthy' },
  { value: 'fresh', type: 'root', meaning: 'new, recent' },
  { value: 'harm', type: 'root', meaning: 'damage, hurt' },
  { value: 'law', type: 'root', meaning: 'rule, legal' },
  { value: 'lead', type: 'root', meaning: 'guide, direct' },
  { value: 'live', type: 'root', meaning: 'exist, be alive' },
  { value: 'luck', type: 'root', meaning: 'fortune, chance' },
  { value: 'manage', type: 'root', meaning: 'control, handle' },
  { value: 'measure', type: 'root', meaning: 'determine size' },
  { value: 'notice', type: 'root', meaning: 'observe, see' },
  { value: 'order', type: 'root', meaning: 'arrangement' },
  { value: 'pay', type: 'root', meaning: 'give money' },
  { value: 'point', type: 'root', meaning: 'indicate, tip' },
  { value: 'predict', type: 'root', meaning: 'forecast' },
  { value: 'prepare', type: 'root', meaning: 'make ready' },
  { value: 'produce', type: 'root', meaning: 'make, create' },
  { value: 'quick', type: 'root', meaning: 'fast, rapid' },
  { value: 'quiet', type: 'root', meaning: 'silent, calm' },
  { value: 'reason', type: 'root', meaning: 'logic, cause' },
  { value: 'regard', type: 'root', meaning: 'consider' },
  { value: 'secure', type: 'root', meaning: 'safe, protected' },
  { value: 'sense', type: 'root', meaning: 'feel, perceive' },
  { value: 'settle', type: 'root', meaning: 'establish' },
  { value: 'shame', type: 'root', meaning: 'embarrassment' },
  { value: 'skill', type: 'root', meaning: 'ability' },
  { value: 'succeed', type: 'root', meaning: 'achieve goal' },
  { value: 'taste', type: 'root', meaning: 'flavor, sense' },
  { value: 'teach', type: 'root', meaning: 'instruct' },
  { value: 'time', type: 'root', meaning: 'duration' },
  { value: 'tire', type: 'root', meaning: 'exhaust' },
  { value: 'truth', type: 'root', meaning: 'fact, reality' },
  { value: 'understand', type: 'root', meaning: 'comprehend' },
  { value: 'view', type: 'root', meaning: 'see, perspective' },
  { value: 'worth', type: 'root', meaning: 'value' },
]

// Color classes for morpheme types
export const MORPHEME_COLORS = {
  prefix: {
    bg: 'bg-blue-50',
    text: 'text-blue-700',
    hover: 'hover:bg-blue-100',
    solid: 'bg-blue-500'
  },
  root: {
    bg: 'bg-green-50',
    text: 'text-green-700',
    hover: 'hover:bg-green-100',
    solid: 'bg-green-500'
  },
  suffix: {
    bg: 'bg-purple-50',
    text: 'text-purple-700',
    hover: 'hover:bg-purple-100',
    solid: 'bg-purple-500'
  }
}